SoftwareTechnology/Controllers/AdminsController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SoftwareTechnology.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SoftwareTechnology.Controllers
{
    public class AdminsController : Controller
    {
        private readonly ApplicationDbContext _db;
        [BindProperty]
        public Admin admin { get; set; }
        [BindProperty]
        public VaccineCentre vaccineCentre { get; set; }
        public AdminsController(ApplicationDbContext db)
        {
            _db = db;
        }
        

        [HttpGet]
        public IActionResult AdminLogIn()
        {
            HttpContext.Session.Clear();
            return View();
        }

        [HttpPost]
        public IActionResult AdminLogIn(Admin model)
        {
            if (ModelState.IsValid)
            {
                admin = _db.Admins.FirstOrDefault(admin => admin.username == model.username
                 && admin.password == model.password);

                if (admin != null)
                {
                    HttpContext.Session.SetString("admin",admin.username);

                    return RedirectToAction("AdminHome");
                }

                ModelState.AddModelError(string.Empty, "Δέν βρέθηκε χρήστης με αυτά τα στοιχεία");
            }

            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.Any, NoStore = true)]
        public IActionResult AdminHome()
        {
            if (HttpContext.Session.GetString("admin") != null)
            {
                ViewBag.admin=HttpContext.Session.GetString("admin");
                int countcit = _db.Citizens.Count();
                ViewBag.countCIT = countcit;
                int countemp = _db.Employees.Count();
                ViewBag.countEMP = countemp;
                int countvc = _db.VaccineCentres.Count();
                ViewBag.countVC = countvc;

                var result = _db.VaccineCentres.ToList();
                return View(result);

            }
            else
            {
                return RedirectToAction("AdminLogIn");
            }

           
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.Any, NoStore = true)]
        public IActionResult AddVaccineCentre()
        {
            if (HttpContext.Session.GetString("admin") != null)
            {
                return View();
            }
            else
            {
                return RedirectToAction("AdminLogIn");
            }

            
        }
        [HttpPost]
        public IActionResult AddVaccineCentre(VaccineCentre model)
        {
            if (ModelState.IsValid)
            {
                VaccineCentre vc= _db.VaccineCentres.FirstOrDefault(vaccineCentre => vaccineCentre.Name.Equals(model.Name) && vaccineCentre.Township.Equals(model.Township));
                if (vc==null)
                {
                    _db.VaccineCentres.Add(model);
                    _db.SaveChanges();
                   
                    return RedirectToAction("AdminHome");
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Το Εμβολιαστικό Κέντρο υπάρχει ήδη");
                }



            }

            return View();
        }

        public IActionResult LogOut()
        {
            return RedirectToAction("AdminLogIn");
        }

        public IActionResult DeleteVaccineCentre(int id)
        {
            vaccineCentre = _db.VaccineCentres.FirstOrDefault(vc => vc.ID == id);
            int count = _db.Appointments.Count(ap => ap.vaccineCentreID == vaccineCentre.ID);
            if (count== 0)
            {
                _db.VaccineCentres.Remove(vaccineCentre);
                _db.SaveChanges();
            }
            else
            {
                HttpContext.Session.SetString("msg", "true");
            }
            
            return RedirectToAction("AdminHome");

        }
    }
}

SoftwareTechnology/Views/Admins/AddVaccineCentre.cshtml
@model VaccineCentre

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Admin Login</title>
    <style>
        .divider:after,
        .divider:before {
            content: "";
            flex: 1;
            height: 1px;
            background: #eee;
        }

        .h-custom {
            height: calc(100% - 73px);
        }

        @@media (max-width: 450px) {
            .h-custom {
                height: 100%;
            }
        }
    </style>

</head>
<body>

    <br /><br /><br />

    <div class="row d-flex justify-content-center align-items-center  ">
        <div class="col-md-9 col-lg-6 col-xl-5 ">
            <img src="~/img/vcCentre.jpg"
                 class="img-fluid" alt="Sample image">
        </div>
        <div class="col-md-8 col-lg-6 col-xl-6 offset-xl-1">
            <form method="post" action="AddVaccineCentre">


                <div class="divider d-flex align-items-center my-4">

                    <p class="text-center h3 fw-bold mx-1 mb-0">Προσθήκη Εμβολιαστικού Κέντρου</p>
                </div>
                <br />

                <!-- Email input -->
                <div class="form-group">
                    <label class="form-label  h5" asp-for="Name">Όνομα Εμβολιαστικού Κέντρου</label>
                    <input asp-for="Name" class="form-control form-control-lg"
                           placeholder="Εισάγετε Όνομα Κέντρου" required onkeypress="CheckSpace(event)"/>

                </div>
                <br />
                <!-- Password input -->
                <div class="form-group row">

                    <div class="col-6 col-md-8  ">
                        <label class="form-label h5" asp-for="Township">Περιοχή Εμβολιαστικού Κέντρου</label>
                    </div>

                    <div class="h5 col-6 col-md-2">
                        @Html.DropDownListFor(t => t.Township,
                    new SelectList(Enum.GetNames(typeof(Townships))),
                    "Επέλεξε Δήμο",
                    new { @required = "required" })
                    </div>
                    <div class=" col-xl-10 offset-3 ">
                        <div asp-validation-summary="All" class=" text-danger" style="list-style: none; margin-left: -40px"></div>

                    </div>
                        

                    
                    

                </div>
                

                <div class="text-center text-lg-start ">
                    <button type="submit" class="btn btn-primary btn-lg"
                            style="padding-left: 2.5rem; background-color: #003476; padding-right: 2.5rem;">
                        Προσθήκη
                    </button>


                </div>

            </form>
        </div>


    </div>




</body>
</html>

<script>
    function CheckSpace(event) {
        if (event.which == 32) {
            event.preventDefault();
            return false;
        }
    }
</script>

SoftwareTechnology/Views/Admins/AdminHome.cshtml
@model List<VaccineCentre>
@using Microsoft.AspNetCore.Http

@inject IHttpContextAccessor httpContext


<!DOCTYPE html>
<html dir="ltr" lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="keywords"
          content="wrappixel, admin dashboard, html css dashboard, web dashboard, bootstrap 5 admin, bootstrap 5, css3 dashboard, bootstrap 5 dashboard, Ample lite admin bootstrap 5 dashboard, frontend, responsive bootstrap 5 admin template, Ample admin lite dashboard bootstrap 5 dashboard template">
    <meta name="description"
          content="Ample Admin Lite is powerful and clean admin dashboard template, inpired from Bootstrap Framework">
    <meta name="robots" content="noindex,nofollow">


    <link href="~/css/admin/chartist.min.css" rel="stylesheet">
    <link rel="stylesheet" href="~/css/admin/chartist-plugin-tooltip.css">
    <link href="~/css/admin/style.min.css" rel="stylesheet">
</head>

<body>




    <!-- ============================================================== -->
    <!-- Main wrapper - style you can find in pages.scss -->
    <!-- ============================================================== -->
    <!-- Page wrapper  -->
    <!-- ============================================================== -->
    <div class="page-wrapper border">
        <!-- ============================================================== -->
        <!-- Bread crumb and right sidebar toggle -->
        <!-- ============================================================== -->
        <div class="page-breadcrumb bg-white">
            <div class="row align-items-center ">
                <div class="col-md-6">
                    <h4 class="page-title">Καλώς ήρθες @ViewBag.admin</h4>
                </div>
                <div class="col-md-6 text-right">
                    <a asp-action="LogOut" asp-controller="Admins" class="btn btn-info text-white btn-outline-secondary">Αποσύνδεση</a>

                </div>

            </div>
            <!-- /.col-lg-12 -->
        </div>
        <!-- ============================================================== -->
        <!-- End Bread crumb and right sidebar toggle -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- Container fluid  -->
        <!-- ============================================================== -->
        <div class="container-fluid " style="background-color: #f8f9fc">
            <!-- ============================================================== -->
            <!-- Three charts -->
            <!-- ============================================================== -->
            <div class="row justify-content-center">
                <div class="col-lg-4 col-md-12">
                    <div class="white-box analytics-info">
                        <h3 class="box-title">Συνολικοί Εγγεγραμένοι Πολίτες</h3>
                        <ul class="list-inline two-part d-flex align-items-center mb-0">
                            <li>
                                <div id="sparklinedash">
                                    <canvas width="67" height="30"
                                            style="display: inline-block; width: 67px; height: 30px; vertical-align: top;"></canvas>
                                </div>
                            </li>
                            <li class="ms-auto"><span class="counter text-success">@ViewBag.countCIT</span></li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-4 col-md-12">
                    <div class="white-box analytics-info">
                        <h3 class="box-title">Συνολικοί Υπάληλλοι</h3>
                        <ul class="list-inline two-part d-flex align-items-center mb-0">
                            <li>
                                <div id="sparklinedash2">
                                    <canvas width="67" height="30"
                                            style="display: inline-block; width: 67px; height: 30px; vertical-align: top;"></canvas>
                                </div>
                            </li>
                            <li class="ms-auto"><span class="counter text-purple">@ViewBag.countEMP</span></li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-4 col-md-12">
                    <div class="white-box analytics-info">
                        <h3 class="box-title">Συνολικά Εμβολιαστικά Κέντρα</h3>
                        <ul class="list-inline two-part d-flex align-items-center mb-0">
                            <li>
                                <div id="sparklinedash3">
                                    <canvas width="67" height="30"
                                            style="display: inline-block; width: 67px; height: 30px; vertical-align: top;"></canvas>
                                </div>
                            </li>
                            <li class="ms-auto">
                                <span class="counter text-info">@ViewBag.countVC</span>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            <!-- ============================================================== -->
            <!--  -->
            <!-- ============================================================== -->
            <div class="row">
                <div class="col-md-12 col-lg-12 col-sm-12 col-xs-12">
                    <div class="white-box">
                        <h3 class="box-title">Δραστηριότητα Επισκέψεων 2021</h3>
                        <div class="d-md-flex">
                            <ul class="list-inline d-flex ms-auto">
                                <li class="ps-3">
                                    <h5 class="text-info">Πολίτες</h5>
                                </li>
                                <li class="ps-3">
                                    <h5 class="text-inverse">Υπάλληλοι</h5>
                                </li>
                            </ul>
                        </div>
                        <div id="ct-visits" style="height: 405px;">
                            <div class="chartist-tooltip" style="top: -17px; left: -12px;">
                                <span class="chartist-tooltip-value">6</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- ============================================================== -->
            <!-- -->
            <!-- ============================================================== -->
            <div class="row">
                <div class="col-md-12 col-lg-12 col-sm-12">
                    <div class="white-box row align-items-center">


                        <div class="col-md-6 ">
                            <h1>Προβολή Εμβολιαστικών Κέντρων</h1>
                        </div>
                        <div class="col-md-6 text-right ">
                            <a type="submit" value="View Vaccine Centres" asp-action="AddVaccineCentre" asp-controller="Admins" class="btn btn-info text-white btn-outline-secondary " style="font-size:17px;">Προσθήκη Εμβολιαστικού Κέντρου</a>

                        </div>


                        <div class="container row p-0 m-0">

                            <div class="col-12 border p-3">
                                <table class="table table-striped table-bordered" style="width:100%" id="DT_load">

                                    <thead>
                                        <tr>
                                            <th>Όνομα Εμβολιαστικού Κέντρου</th>
                                            <th>Περιοχή Εμβολιαστικού Κέντρου</th>
                                            <th></th>
                                        </tr>

                                    </thead>

                                    @foreach (var item in Model)
                                    {
                                        <tr>
                                            <td>@item.Name</td>
                                            <td>@item.Township</td>
                                            <td class="text-center"><a type="submit" asp-action="DeleteVaccineCentre" asp-controller="Admins" asp-route-id="@item.ID" class="btn btn-danger text-white btn-outline-secondary " >Διαγραφή</a></td>
                                        </tr>
                                    }

                                </table>
                                <br />
                                @{
                                    if (httpContext.HttpContext.Session.GetString("msg") == "true")
                                    {
                                        <div class="alert alert-danger text-center" role="alert" id="scroll">
                                            <h5>Δεν μπορεί να γίνει διαγραφή εμβολιαστικού κέντρου όταν υπάρχουν κλεισμένα ραντεβού </h5>
                                        </div>

                                        httpContext.HttpContext.Session.Remove("msg");
                                    }
                                }
                            </div>
                        </div>



                    </div>
                    <br /><br />
                </div>
            </div>


        </div>

    </div>

    <script src="~/js/admin/jquery.min.js"></script>
    <!-- Bootstrap tether Core JavaScript -->


    <script src="~/js/admin/jquery.sparkline.min.js"></script>
    <!--Wave Effects -->
    <!--Menu sidebar -->
    <!--Custom JavaScript -->
    <script src="~/js/admin/custom.js"></script>
    <!--This page JavaScript -->
    <!--chartis chart-->
    <script src="~/js/admin/chartist.min.js"></script>
    <script src="~/js/admin/chartist-plugin-tooltip.min.js"></script>
    <script src="~/js/admin/dashboard1.js"></script>
    <script src="~/js/DataTable.js"></script>
</body>

</html>

<script>
    document.getElementById('scroll').scrollIntoView();
</script>

SoftwareTechnology/Views/Admins/AdminLogIn.cshtml
@model Admin

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Admin Login</title>
    <style>
        .divider:after,
        .divider:before {
            content: "";
            flex: 1;
            height: 1px;
            background: #eee;
        }

        .h-custom {
            height: calc(100% - 73px);
        }

        @@media (max-width: 450px) {
            .h-custom {
                height: 100%;
            }
        }
    </style>

</head>
<body style="background-color: #fefbfc;">

    <br />

    <div class="card " style="border-radius: 1rem;">
        <br /><br />
        <div class="container-fluid h-custom">
            <div class="row d-flex justify-content-center align-items-center h-100">
                <div class="col-md-9 col-lg-6 col-xl-5">
                    <img src="~/img/draw2.webp"
                         class="img-fluid" alt="Sample image">
                </div>
                <div class="col-md-8 col-lg-6 col-xl-4 offset-xl-1">
                    <form method="post">


                        <div class="divider d-flex align-items-center my-4">

                            <p class="text-center h3 fw-bold mx-1 mb-0">Σύνδεση Διαχειριστή</p>
                        </div>
                        <br />
                        <!-- Email input -->
                        <div class="form-group">
                            <label class="form-label  h5" asp-for="username">Όνομα χρήστη</label>
                            <input asp-for="username" class="form-control form-control-lg"
                                   placeholder="Εισάγετε Όνομα χρήστη" required onkeypress="CheckSpace(event)" />

                        </div>

                        <!-- Password input -->
                        <div class="form-group">



                            <label class="form-label h5 " asp-for="password">Κωδικός πρόσβασης</label>
                            <input asp-for="password" type="password" class="form-control form-control-lg"
                                   placeholder="Εισάγετε Κωδικό πρόσβασης" required onkeypress="CheckSpace(event)" />

                        </div>

                        <div asp-validation-summary="All" class="text-danger" style="font-size:15px;">


                        </div>
                        <div class="text-center text-lg-start ">
                            <button type="submit" class="btn btn-primary btn-lg"
                                    style="padding-left: 2.5rem; background-color: #003476; padding-right: 2.5rem;">
                                Σύνδεση
                            </button>

                        </div>

                    </form>
                </div>
            </div>
        </div>
        <br /><br /><br /><br />

    </div>


</body>
</html>



<script>
    function CheckSpace(event) {
        if (event.which == 32) {
            event.preventDefault();
            return false;
        }
    }

</script>