SoftwareTechnology/Models/Citizen.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace SoftwareTechnology.Models
{
    public class Citizen
    {
        
        public String Name { get; set; }
        
        public String Surname { get; set; }
        [Key]
        public String AMKA { get; set; }
        public String ContactNumber { get; set; }

        public String Township { get; set; }

        
        public int Dose { get; set; } = 0;

        
        public String username { get; set; }
        
        public String password { get; set; }



       

    }

   
}

SoftwareTechnology/Controllers/CitizensController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using SoftwareTechnology.Models;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Threading.Tasks;


namespace SoftwareTechnology.Controllers
{
    
    public class CitizensController : Controller
    {

        private readonly ApplicationDbContext _db;
        [BindProperty]
        public Citizen citizen { get; set; }
        [BindProperty]
        public MultipleClassJoin multipleClass { get; set; }
        public CitizensController(ApplicationDbContext db)
        {
            _db = db;
            
        }

        
        public IActionResult CitizenLogIn()
        {
            HttpContext.Session.Clear();
            return View();
        }

        [HttpPost]
        public IActionResult CitizenLogIn(Citizen model)
        {
            
            if (ModelState.IsValid)
            {
                citizen = _db.Citizens.FirstOrDefault(cit => cit.username== model.username
                 && cit.password == model.password);

                

                if (citizen != null)
                {
                    HttpContext.Session.SetString("citizenAMKA", citizen.AMKA);
                    
                    return RedirectToAction("CitizenHome");
                }

                ModelState.AddModelError(string.Empty, "Δέν βρέθηκε χρήστης με αυτά τα στοιχεία");
            }

            return View(model);
        }

        public IActionResult CitizenSignUp()
        {
            return View();
        }

        [HttpPost]
        public IActionResult CitizenSignUp(Citizen model)
        {
            if (ModelState.IsValid)
            {
                Citizen citizen = _db.Citizens.FirstOrDefault(cit => cit.AMKA.Equals(model.AMKA));

                if (citizen == null)
                {
                    Citizen citizen1= _db.Citizens.FirstOrDefault(cit => cit.username.Equals(model.username));
                    if (citizen1 == null)
                    {
                        _db.Citizens.Add(model);
                        _db.SaveChanges();
                        return RedirectToAction("CitizenLogIn");
                    }
                    else
                    {
                        ModelState.AddModelError(string.Empty, "Το Όνομα χρήστη υπάρχει ήδη");
                        return View();
                    }

                    
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Το ΑΜΚΑ υπάρχει ήδη");
                }

            }

            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.Any, NoStore = true)]
        public IActionResult CitizenHome()
        {
           
            if (HttpContext.Session.GetString("citizenAMKA") != null)
            {
                multipleClass = new MultipleClassJoin();
                string amka = HttpContext.Session.GetString("citizenAMKA");
                citizen = _db.Citizens.FirstOrDefault(cit => cit.AMKA.Equals(amka));

                multipleClass.citizen = citizen;
                if (citizen.Dose < 2)
                {

                    if (citizen.Dose == 1)
                    {
                        citizen.Dose--;
                        _db.SaveChanges();
                    }


                    var vcList = _db.VaccineCentres.Where(vc => vc.Township == citizen.Township).ToList();


                    multipleClass.vaccineCentreList = vcList;

                }
                else
                {

                    List<Appointment> aplist = _db.Appointments.Where(cit => cit.citizenAMKA == citizen.AMKA).ToList();
                    List<VaccineCentre> vaccineCentres = new List<VaccineCentre>();

                    foreach (var item in aplist)
                    {
                        vaccineCentres.Add((VaccineCentre)_db.VaccineCentres.FirstOrDefault(vc => vc.ID == item.vaccineCentreID));
                    }

                    multipleClass.appointmentList = aplist;
                    multipleClass.vaccineCentreList = vaccineCentres;

                }



                return View(multipleClass);
            }
            else
            {
                return RedirectToAction("CitizenLogIn");
            }

            
        }
        [HttpPost]
        public IActionResult CitizenHome(int Selected,String firstdose,String secdose)
        {

            
            ViewBag.Selected = Selected;
            multipleClass = new MultipleClassJoin();
            string amka = HttpContext.Session.GetString("citizenAMKA");
            citizen = _db.Citizens.FirstOrDefault(cit => cit.AMKA.Equals(amka));



            if (secdose != null)
            {

                HttpContext.Session.SetString("secDose", secdose);
                HttpContext.Session.SetInt32("vc2", Selected);
                

                if (citizen.Dose == 1)
                {
                    DateTime dt1 = DateTime.Parse(HttpContext.Session.GetString("firstDose"), null, System.Globalization.DateTimeStyles.RoundtripKind);

                    Appointment ap1 = new Appointment();
                    ap1.citizenAMKA = citizen.AMKA;
                    ap1.Date = dt1.Date;
                    ap1.Time = dt1.TimeOfDay;
                    ap1.vaccineCentreID = (int)HttpContext.Session.GetInt32("vc1");
                    _db.Appointments.Add(ap1);

                    DateTime dt2 = DateTime.Parse(HttpContext.Session.GetString("secDose"), null, System.Globalization.DateTimeStyles.RoundtripKind);

                    Appointment ap2 = new Appointment();
                    ap2.citizenAMKA = citizen.AMKA;
                    ap2.Date = dt2.Date;
                    ap2.Time = dt2.TimeOfDay;
                    ap2.vaccineCentreID = Selected;
                    _db.Appointments.Add(ap2);
                    citizen.Dose++;
                    _db.SaveChanges();
                }

                
                

            }
            else if (firstdose != null)
            {
                
                if (citizen.Dose==0)
                {  
                    HttpContext.Session.SetString("firstDose",firstdose);
                    
                    HttpContext.Session.SetInt32("vc1", Selected);
                    citizen.Dose++;
                    _db.SaveChanges();
                 
                    
                }


            }

            var vcList = _db.VaccineCentres.Where(vc => vc.Township == citizen.Township).ToList();
            var resap = (

               from vc in _db.VaccineCentres
               join ap in _db.Appointments
               on vc.ID equals ap.vaccineCentreID
               where vc.ID == Selected
               select new Appointment
               {
                   ID = ap.ID,
                   citizenAMKA = ap.citizenAMKA,
                   Date = ap.Date,
                   Time = new TimeSpan(ap.Time.Hours, ap.Time.Minutes, ap.Time.Seconds),
                   vaccineCentreID = ap.vaccineCentreID

               }


           ).ToList();


            
           
            
                
            
            multipleClass.citizen = citizen;
            if (citizen.Dose < 2)
            {
                multipleClass.appointmentList = resap;
                multipleClass.vaccineCentreList = vcList;
            }
            else
            {
                List<VaccineCentre> vclist2 = new List<VaccineCentre>();
                var aplist = _db.Appointments.Where(cit => cit.citizenAMKA == citizen.AMKA).ToList();
                
               
                vclist2.Add(_db.VaccineCentres.FirstOrDefault(vc => vc.ID == aplist[0].vaccineCentreID));
                vclist2.Add(_db.VaccineCentres.FirstOrDefault(vc => vc.ID == aplist[1].vaccineCentreID));
                
                
                multipleClass.appointmentList = aplist;
                multipleClass.vaccineCentreList = vclist2;
            }

            return View(multipleClass);
        }

        public IActionResult LogOut()
        {
            return RedirectToAction("CitizenLogIn");
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.Any, NoStore = true)]
        public IActionResult EditCitizen()
        {
            if (HttpContext.Session.GetString("citizenAMKA") != null)
            {
                string tmp = HttpContext.Session.GetString("citizenAMKA");
                citizen = _db.Citizens.FirstOrDefault(citizen => citizen.AMKA.Equals(tmp));


                return View(citizen);
            }
            else
            {
                return RedirectToAction("CitizenLogIn");
            }
        }

        [HttpPost]
        public IActionResult EditCitizen(Citizen model)
        {
            if (ModelState.IsValid)
            {
                Citizen cit = _db.Citizens.FirstOrDefault(cit => cit.username == model.username && cit.AMKA != model.AMKA);
                if (cit != null)
                {
                    ModelState.AddModelError(string.Empty, "Το όνομα χρήστη υπάρχει ήδη");
                }
                else
                {
                    _db.Citizens.Update(model);
                    _db.SaveChanges();

                    return RedirectToAction("CitizenHome");
                }


            }
            return View(model);
        }


        public IActionResult DeleteAppointment()
        {
            string amka = HttpContext.Session.GetString("citizenAMKA");
            citizen = _db.Citizens.FirstOrDefault(cit => cit.AMKA.Equals(amka));

            List<Appointment> aplist = _db.Appointments.Where(cit => cit.citizenAMKA == citizen.AMKA).ToList();

            string app1 = aplist[0].Date.ToString("yyyy-MM-dd") + " "+ aplist[0].Time.ToString();

SoftwareTechnology/Views/Citizens/CitizenLogIn.cshtml
@model Citizen
<html>


<body>

    <section class="text-center">
        <!-- Background image -->
        <div class="p-5 bg-image" style=" background-image: url('https://www.lse.ac.uk/international-relations/assets/images/page-headers/covid19-1400x300.jpg'); 
      height: 270px; background-size: contain; "></div>
        <!-- Background image -->

        <div class="card mx-4 mx-md-5 shadow-5-strong" style="
        margin-top: -100px;
        background: hsla(0, 0%, 100%, 0.8);
        backdrop-filter: blur(30px);
        ">
            <div class="card-body py-1 px-md-5">

                <div class="row d-flex justify-content-center">
                    <div class="col-lg-8">
                        <br />
                        <h2 class="fw-bold mb-3">Σύνδεση Πολίτη</h2>
                        <form method="post">

                            <div class="form-outline mb-4">
                                <input type="text" id="form3Example4" class="form-control" asp-for="username" placeholder="Εισάγετε Όνομα χρήστη" required onkeypress="CheckSpace(event)" />
                                <label class="form-label h5" for="form3Example4" asp-for="username">Όνομα Χρήστη</label>
                            </div>

                            <div class="form-outline mb-4">
                                <input type="password" id="form3Example4"  placeholder="Εισάγετε Κωδικό πρόσβασης" class="form-control" asp-for="password" required onkeypress="CheckSpace(event)" />
                                <label class="form-label h5" for="form3Example4" asp-for="password">Κωδικός Πρόσβασης</label>
                            </div>

                            <div class=" form-outline mb-4 col-xl-10 offset-2  text-left">
                                <div asp-validation-summary="All" class=" text-danger"></div>

                            </div>
                            <!-- Submit button -->
                            <button type="submit" class="btn btn-primary btn-block mb-4">
                                Σύνδεση
                            </button>

          
                             <p class="text-center text-muted mt-5 mb-0 ">Δεν Εχετε Λογαριαμό; <a asp-action="CitizenSignUp" asp-controller="Citizens" class="text-success "> Δημιουργία Λογαριασμού</a></p>

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>


</body>

</html>

<script>
    function CheckSpace(event) {
        if (event.which == 32) {
            event.preventDefault();
            return false;
        }
    }

</script>

SoftwareTechnology/Views/Citizens/CitizenSignUp.cshtml
@model Citizen
<html>


<body>

    <section class="text-center">
        <!-- Background image -->
        <div class="p-5 bg-image border-5" style=" background-image: url('https://www.zva.gov.lv/sites/default/files/styles/header_carousel_slide/public/carousel/www_augsa2_2_2.jpg?itok=L66IiJAH'); height: 280px; background-size: 100% 100% "></div>
        <!-- Background image -->

        <div class="card mx-4 mx-md-5 shadow-5-strong" style="
        margin-top: -100px;
        background: hsla(0, 0%, 100%, 0.8);
        backdrop-filter: blur(30px);
        ">
            <div class="card-body py-1 px-md-5">

                <div class="row d-flex justify-content-center">
                    <div class="col-lg-8">
                        <br />
                        <h2 class="fw-bold mb-5">Εγγραφή Πολίτη</h2>
                        <form method="post" action="CitizenSignUp">


                            <div class="row">
                                <div class="col-md-6 mb-4">
                                    <div class="form-outline">
                                        <input type="text" class="form-control" asp-for="Name" required onkeypress="CheckSpace(event)" />
                                        <label class="form-label h6" asp-for="Name">Όνομα* </label>
                                    </div>
                                </div>
                                <div class="col-md-6 mb-4">
                                    <div class="form-outline">
                                        <input type="text" id="form3Example2" class="form-control" asp-for="Surname" required onkeypress="CheckSpace(event)" />
                                        <label class="form-label h6" for="form3Example2" asp-for="Surname">Επώνυμο*</label>
                                    </div>
                                </div>
                            </div>


                            <div class="form-outline mb-4">
                                <input type="text" pattern="[0-9]+" id="form3Example3" class="form-control" asp-for="AMKA"  maxlength="11" required onkeypress="CheckSpace(event)" />
                                <label class="form-label h6" for="form3Example3" asp-for="AMKA" >ΑΜΚΑ*</label>
                            </div>

                            <div class="form-outline mb-4">
                                <input type="text" pattern="[0-9]+" id="form3Example4" class="form-control" asp-for="ContactNumber"   maxlength="10" onkeypress="CheckSpace(event)" />
                                <label class="form-label h6" for="form3Example4" asp-for="ContactNumber" >Τηλέφωνο</label>
                            </div>


                            <div class="form-outline mb-4">
                                <div>
                                    @Html.DropDownListFor(t => t.Township,
                           new SelectList(Enum.GetNames(typeof(Townships))),
                           "Επιλογή Δήμου",
                           new { @required = "required" })
                                </div>

                                <label class="form-label h6" for="form3Example4" asp-for="Township">Δήμος Κατοικίας*</label>
                            </div>




                            <div class="form-outline mb-4">
                                <input type="text" id="form3Example4" class="form-control" asp-for="username" required onkeypress="CheckSpace(event)" />
                                <label class="form-label h6" for="form3Example4" asp-for="username">Όνομα Χρήστη*</label>
                            </div>

                            <div class="form-outline mb-4">
                                <input type="password" id="form3Example4" class="form-control" asp-for="password" required onkeypress="CheckSpace(event)" />
                                <label class="form-label h6" for="form3Example4" asp-for="password">Κωδικός Πρόσβασης*</label>
                            </div>

                            <div class=" form-outline mb-4 col-xl-10 offset-3  text-left">
                                <div asp-validation-summary="All" class=" text-danger" ></div>

                            </div>
                            <!-- Submit button -->
                            <button type="submit" class="btn btn-primary btn-block mb-4">
                                Εγγραφή
                            </button>



                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>


</body>

</html>

<script>
    function CheckSpace(event) {
        if (event.which == 32) {
            event.preventDefault();
            return false;
        }
    }

</script>

SoftwareTechnology/Views/Citizens/EditCitizen.cshtml
@model Citizen
<!DOCTYPE html>
<html dir="ltr" lang="en">

<head>

    <link href="~/css/admin/style.min.css" rel="stylesheet">

</head>

<body>
   

    <div class="page-wrapper" style="background-color: #f8f9fc">

        <div class="container-fluid col-8 ">


            <div class="card">
                <div class="card-body">
                    <form class="form-horizontal form-material" method="post">
                        <div class="form-group mb-4">
                            <label class="col-md-12 p-0" asp-for="username">Όνομα Χρήστη</label>
                            <div class="col-md-12 border-bottom p-0">
                                <input type="text" asp-for="username" value="@Model.username" required class="form-control p-0 border-0" onkeypress="CheckSpace(event)">
                            </div>
                        </div>
                        <div class="form-group mb-4">
                            <label class="col-md-12 p-0" asp-for="Name">Όνομα</label>
                            <div class="col-md-12 border-bottom p-0">
                                <input type="text" asp-for="Name" value="@Model.Name" class="form-control p-0 border-0" onkeypress="CheckSpace(event)">
                            </div>
                        </div>
                        <div class="form-group mb-4">
                            <label class="col-md-12 p-0" asp-for="Surname">Επώνυμο</label>
                            <div class="col-md-12 border-bottom p-0">
                                <input type="text" asp-for="Surname" value="@Model.Surname" class="form-control p-0 border-0" onkeypress="CheckSpace(event)">
                            </div>
                        </div>
                        <div class="form-group mb-4">
                            <label for="example-email" class="col-md-12 p-0" asp-for="AMKA">AMKA</label>
                            <div class="col-md-12 border-bottom p-0">
                                <input class="form-control p-0 border-0" type="text" asp-for="AMKA" value="@Model.AMKA" readonly style="color:darkgrey">
                            </div>
                        </div>

                        <div class="form-group mb-4">
                            <label class="col-md-12 p-0" asp-for="ContactNumber">Τηλέφωνο</label>
                            <div class="col-md-12 border-bottom p-0">
                                <input type="text" pattern="[0-9]+" asp-for="ContactNumber"  maxlength="10" placeholder="@Model.ContactNumber"
                                       class="form-control p-0 border-0" onkeypress="CheckSpace(event)">
                            </div>
                        </div>

                        <div class="form-group mb-4">
                            <label class="col-md-12 p-0" asp-for="Township">Δήμος Κατοικίας</label>
                            <div class="col-md-12 border-bottom p-0">

                                @Html.DropDownListFor(t => t.Township,
                                new SelectList(Enum.GetNames(typeof(Townships)),Model.Township))
                                

                               

                            </div>
                        </div>

                        <input hidden type="text" asp-for="password" />
                        <input hidden type="text" asp-for="Dose" />
                        <div class=" col-xl-12  h5 ">
                            <div asp-validation-summary="All" class=" text-danger" list-style: none;></div>

                        </div>
                        <div class="form-group mb-4">
                            <div class="col-sm-12 text-center">
                                <button type="submit" asp-action="EditCitizen" asp-controller="Citizens" class="btn btn-success  text-white btn-outline-secondary">Ενημέρωση</button>
                            </div>
                        </div>

                    </form>
                </div>
            </div>

          
        </div>
       

    </div>
 

    <script src="~/js/admin/jquery.min.js"></script>
   
    <script src="~/js/admin/custom.js"></script>

</body>

</html>

<script>

    function CheckSpace(event) {
        if (event.which == 32) {
            event.preventDefault();
            return false;
        }
    }
</script>